version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: 'friday'
      time: '20:00'
      timezone: 'Europe/Amsterdam'
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 100
    labels:
      - 'npm'
      - 'dependencies'
    reviewers:
      - moranje
      - jorisj
    assignees:
      - moranje
      - jorisj
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
  # Fetch and update latest `github-actions` pkgs
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: 'friday'
      time: '20:00'
      timezone: 'Europe/Amsterdam'
    open-pull-requests-limit: 100
    reviewers:
      - moranje
      - jorisj
    assignees:
      - moranje
      - jorisj
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
